### ISSUE TITLE
Fix the layout of team members in team page

### ISSUE THREAD

**Issue by swatism** [shikshaplus/pareeksha-manch#7]
Few member of the team are not properly visible in layout.
See 
![screenshot from 2018-09-17 07-05-22](https://user-images.githubusercontent.com/42741015/45603264-ff998500-ba19-11e8-8dbb-6bd5283e012f.png)

**Comment by thapatechnical** [comment]
Ok.

**Comment by dharambir** [comment]
Actually, Some images like the person of "Venkatesh", "Shraddha Sonawane" and "Akanksha Agarwal" are more bigger all should be "256X256".

**Comment by nisusam** [comment]
@dharambir You are right...
You can get the list over here https://www.iconfinder.com/iconsets/marvel-heroes-1
Update all with 256x256
