### ISSUE TITLE
Create a model design for Question Entity

### ISSUE THREAD

**Issue by budhram** [shikshaplus/pareeksha-manch#9]
A Question entity is super class and will have many sub-classes.
Class
        |---- Objective Type
        |---- Subjective Type

And has following attributes
- No of Options
- Correct Answer
- Solution
- Difficulty Level

Let me know your inputs @nisusam @akanksha007

Adding the screenshot during our f2f brainstorm.
![img_20180919_110143](https://user-images.githubusercontent.com/1132451/45732816-a5581a00-bbfb-11e8-9248-35387ee3313e.jpg)

**Comment by gyanbarpaki** [comment]
Closing as it is done.
